### ISSUE TITLE
File Picker opens behind Insert/Edit Window

### ISSUE THREAD

**Issue by franckflo** [cswendrowski/FoundryVTT-TinyMCE-CustomFilePicker#4]
Hi, when I try to pick a file to insert into a journal entry, the file picker opens but it is behind the Insert/Edit Window and therefore I cannot pick an image.
![File Picker](https://user-images.githubusercontent.com/80221412/112568063-22e9db80-8d9f-11eb-85b8-9316a21b08e7.png)

**Comment by SalieriC** [comment]
I have this as well in Foundry 0.7.9 and SWADE 0.17.2.
Unfortunately breaks the entire module. :-S

**Comment by PhilMC157** [comment]
Same here. Foundry 0.7.9
I hope you haven't abandoned this module, yet. ;-)
Because i think it's a very useful one!

**Comment by cswendrowski** [comment]
Hey all - the z-Index issues continue to be a problem due to this not being in Core, where there's more control over the z-Index in relation to other windows.

Luckily, this is being absorbed into core in the near future! https://gitlab.com/foundrynet/foundryvtt/-/issues/358

I apologize that the module version of this has so many conflicts, but please look forward to the core version which should resolve these issues
